1. Import Library

In [36]:
import pandas as pd

2. Load Dataset

In [37]:
df = pd.read_excel("C:/Users/r/OneDrive/Desktop/coding/project team fg/mining 2/data/Database Seara Data.xlsx")
print(df.head(2))

                Timestamp                     Nama Lengkap  \
0 2026-01-27 02:56:47.327  Aarif Rahmaan Jalaluddin Faqiih
1 2026-01-19 09:35:53.999              Abdullah Rajab Sani

                     Email Nomor WhatsApp     Domisili  \
0       aarifrjf@gmail.com   082242458593  Jawa Tengah
1  abdullahrsani@gmail.com   089636422658       Padang

  Apakah Anda Mahasiswa / Fresh Graduate Pekerjaan & Instansi Saat Ini  \
0                                     Ya                     Mahasiswa
1                                     Ya                     belum ada

    Tools yang Ingin Dipelajari  \
0               Python, Tableau
1  Excel, SQL, Python, Power BI

                            Target Join Komunitas Tau Seara Data Dari Mana?  \
0                 Cari Kerja, Upskill, Networking                  LinkedIn
1  Cari Kerja, Upskill, Networking, Switch Career                  LinkedIn

       Column 1        Provinsi  Cari Kerja  Upskill  Networking  \
0  082242458593     Jawa Tengah           1        1           1
1  089636422658  Sumatera Barat           1        1           1

   Switch Career
0              0
1              1

3. Data Understanding

In [38]:
# cek jumlah baris dan kolom
df.shape

(682, 16)

In [39]:
# cek tipe data dan jumlah non-null per kolom
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 16 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Timestamp                               682 non-null    datetime64[us]
 1   Nama Lengkap                            682 non-null    str
 2   Email                                   682 non-null    str
 3   Nomor WhatsApp                          682 non-null    str
 4   Domisili                                682 non-null    str
 5   Apakah Anda Mahasiswa / Fresh Graduate  682 non-null    str
 6   Pekerjaan & Instansi Saat Ini           682 non-null    object
 7   Tools yang Ingin Dipelajari             682 non-null    str
 8   Target Join Komunitas                   682 non-null    str
 9   Tau Seara Data Dari Mana?               682 non-null    str
 10  Column 1                                682 non-null    str
 11  Provinsi                                682 non-null    str
 12  Cari Kerja                              682 non-null    int64
 13  Upskill                                 682 non-null    int64
 14  Networking                              682 non-null    int64
 15  Switch Career                           682 non-null    int64
dtypes: datetime64[us](1), int64(4), object(1), str(10)
memory usage: 85.4+ KB

In [40]:
# cek statistik deskriptif data
df.describe()

,Timestamp,Cari Kerja,Upskill,Networking,Switch Career
count,682,682.000000,682.000000,682.000000,682.000000
mean,2026-01-28 20:42:02.652212,0.661290,0.913490,0.766862,0.400293
min,2026-01-17 20:22:18.629000,0.000000,0.000000,0.000000,0.000000
25%,2026-01-19 10:01:39.747250,0.000000,1.000000,1.000000,0.000000
50%,2026-01-21 08:08:29.092000,1.000000,1.000000,1.000000,0.000000
75%,2026-01-24 19:31:28.081500,1.000000,1.000000,1.000000,1.000000
max,2026-05-17 20:37:28.636000,1.000000,1.000000,1.000000,1.000000
std,NaN,0.473618,0.281322,0.423140,0.490317

In [41]:
# cek tipe data setiap kolom
df.dtypes

Timestamp                                 datetime64[us]
Nama Lengkap                                         str
Email                                                str
Nomor WhatsApp                                       str
Domisili                                             str
Apakah Anda Mahasiswa / Fresh Graduate               str
Pekerjaan & Instansi Saat Ini                     object
Tools yang Ingin Dipelajari                          str
Target Join Komunitas                                str
Tau Seara Data Dari Mana?                            str
Column 1                                             str
Provinsi                                             str
Cari Kerja                                         int64
Upskill                                            int64
Networking                                         int64
Switch Career                                      int64
dtype: object

In [42]:
# cek 2 baris terakhir apakah ada data yang terpotong
df.tail(2)

,Timestamp,Nama Lengkap,Email,Nomor WhatsApp,Domisili,Apakah Anda Mahasiswa / Fresh Graduate,Pekerjaan & Instansi Saat Ini,Tools yang Ingin Dipelajari,Target Join Komunitas,Tau Seara Data Dari Mana?,Column 1,Provinsi,Cari Kerja,Upskill,Networking,Switch Career
680,2026-01-18 08:09:15.194,Zulyan Firdaus,firrzulyann@gmail.com,085756380399,"Bekasi, Jawa Barat",Ya,SAP Rollout Support,"Excel, SQL, Python, Power BI, Looker Studio, D...","Upskill, Networking, Switch Career",LinkedIn,085756380399,Jawa Barat,0,1,1,1
681,2026-01-22 13:20:05.000,Zura Aulia,zuraaa12@gmail.com,085288769002,Jakarta,Ya,-,"Excel, SQL, Python, Tableau","Upskill, Networking",LinkedIn,085288769002,Jakarta,1,1,1,0

In [43]:
# list semua nama kolom untuk cek apakah ada typo pada nama kolom
df.columns.tolist()

['Timestamp',
 'Nama Lengkap',
 'Email',
 'Nomor WhatsApp',
 'Domisili',
 'Apakah Anda Mahasiswa / Fresh Graduate',
 'Pekerjaan & Instansi Saat Ini',
 'Tools yang Ingin Dipelajari',
 'Target Join Komunitas',
 'Tau Seara Data Dari Mana?',
 'Column 1',
 'Provinsi',
 'Cari Kerja',
 'Upskill',
 'Networking',
 'Switch Career']

4. Data Preparation

In [44]:
# cek kolom nama lengkap
print(df["Nama Lengkap"].head(20))

0     Aarif Rahmaan Jalaluddin Faqiih
1                 Abdullah Rajab Sani
2                       Abdur Rochman
3              Abdurrahman Qeis Ahmad
4                  Abid Maulana Akbar
5                  Abimanyu Priyatno
6                 Achmad Chilmi Syifa
7               Achmad jamaah firdaus
8                 Achmad Kurniansyah
9                 Addo Adantya Abiesa
10                        Ade Krisna
11                Ade Krisna Subagyo
12                          Ade Mutia
13                   Ade Tri Oktavian
14                         Adek Putri
15                 Adhyatnika Nugraha
16            Adi Syah Putra Simbolon
17           Adinda Dwi Nur Rahmawati
18                   Adinda Dwi Putri
19                Adinda Putri Satya
Name: Nama Lengkap, dtype: str

In [45]:
# cek nama lengkap yang formatnya kapital semua
df[df["Nama Lengkap"] == df["Nama Lengkap"].str.upper()]["Nama Lengkap"]

67                   AMANG MISBAH
174            DIMAS ARIE PRASOJO
266         GILANG SIDIK RAMADHAN
308                   ILI NOVIANA
404    MUHAMAD RIZA BUDI PRATAMA
524         REFIKA FITRIA GUNAWAN
533               REZA OKTAVIANI
617            SRI AINUN LATHIFAH
Name: Nama Lengkap, dtype: str

In [46]:
# ubah format Nama Lengkap
df["Nama Lengkap"] = df["Nama Lengkap"].str.strip().str.title()

In [47]:
# Mengganti nama kolom sesuai ketentuan
df = df.rename(columns={
    "Tools yang Ingin Dipelajari": "Kemampuan Karyawan",
    "Target Join Komunitas": "Target Masuk Perusahaan",
    "Tau Seara Data Dari Mana?": "Mengetahui Perusahaan Dari Mana?",
    "Apakah Anda Mahasiswa / Fresh Graduate": "Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate"
})

In [48]:
# menghapus kolom yang tidak digunakan
df = df.drop(columns=["Pekerjaan & Instansi Saat Ini", "Column 1"])

In [49]:
# menghapus kolom yang memuat informasi pribadi
df = df.drop(columns=["Nomor WhatsApp", "Email"])

In [50]:
# ubah tipe data timestamp jadi date
df["Timestamp"] = pd.to_datetime(df["Timestamp"]).dt.normalize()

In [51]:
df.head(5)

,Timestamp,Nama Lengkap,Domisili,Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate,Kemampuan Karyawan,Target Masuk Perusahaan,Mengetahui Perusahaan Dari Mana?,Provinsi,Cari Kerja,Upskill,Networking,Switch Career
0,2026-01-27,Aarif Rahmaan Jalaluddin Faqiih,Jawa Tengah,Ya,"Python, Tableau","Cari Kerja, Upskill, Networking",LinkedIn,Jawa Tengah,1,1,1,0
1,2026-01-19,Abdullah Rajab Sani,Padang,Ya,"Excel, SQL, Python, Power BI","Cari Kerja, Upskill, Networking, Switch Career",LinkedIn,Sumatera Barat,1,1,1,1
2,2026-05-17,Abdur Rochman,Surabaya,Ya,"Excel, SQL, Python, Power BI, Databases","Cari Kerja, Upskill, Networking",Teman,Jawa Timur,1,1,1,0
3,2026-01-21,Abdurrahman Qeis Ahmad,Bandung,Ya,"Python, Power BI",Upskill,LinkedIn,Jawa Barat,0,1,0,0
4,2026-01-21,Abid Maulana Akbar,Yogyakarta,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Upskill, Networking, Switch Career",Teman,DI Yogyakarta,0,1,1,1

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 12 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Timestamp                                                            682 non-null    datetime64[us]
 1   Nama Lengkap                                                         682 non-null    str
 2   Domisili                                                             682 non-null    str
 3   Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate  682 non-null    str
 4   Kemampuan Karyawan                                                   682 non-null    str
 5   Target Masuk Perusahaan                                              682 non-null    str
 6   Mengetahui Perusahaan Dari Mana?                                     682 non-null    str
 7   Provinsi                                                             682 non-null    str
 8   Cari Kerja                                                           682 non-null    int64
 9   Upskill                                                              682 non-null    int64
 10  Networking                                                           682 non-null    int64
 11  Switch Career                                                        682 non-null    int64
dtypes: datetime64[us](1), int64(4), str(7)
memory usage: 64.1 KB

In [53]:
print("\nKolom Setelah Preparation")
print(df.columns.tolist())

Kolom Setelah Preparation
['Timestamp', 'Nama Lengkap', 'Domisili', 'Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate', 'Kemampuan Karyawan', 'Target Masuk Perusahaan', 'Mengetahui Perusahaan Dari Mana?', 'Provinsi', 'Cari Kerja', 'Upskill', 'Networking', 'Switch Career']

5. Data Cleaning

In [54]:
# Menghapus spasi di awal dan akhir pada seluruh kolom kategorikal
string_cols = df.select_dtypes(include=["object", "string"]).columns

df[string_cols] = df[string_cols].apply(lambda col: col.str.strip())

In [55]:
# cek duplikat
duplicates = df[df.duplicated()]

print(duplicates)

     Timestamp          Nama Lengkap        Domisili  \
411 2026-04-07  Muhammad Aqlani Wafi  Musi Banyuasin

    Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate  \
411                                                 Ya

                                    Kemampuan Karyawan  \
411  Excel, SQL, Python, Power BI, Looker Studio, D...

             Target Masuk Perusahaan Mengetahui Perusahaan Dari Mana?  \
411  Cari Kerja, Upskill, Networking                         LinkedIn

             Provinsi  Cari Kerja  Upskill  Networking  Switch Career
411  Sumatera Selatan           1        1           1              0

In [56]:
# Menghapus data duplikat
df = df.drop_duplicates()

In [57]:
# Cek apakah ada missing value
df.isnull().sum()

Timestamp                                                              0
Nama Lengkap                                                           0
Domisili                                                               0
Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate    0
Kemampuan Karyawan                                                     0
Target Masuk Perusahaan                                                0
Mengetahui Perusahaan Dari Mana?                                       0
Provinsi                                                               0
Cari Kerja                                                             0
Upskill                                                                0
Networking                                                             0
Switch Career                                                          0
dtype: int64

In [58]:
# simpan data yang sudah menyelesaikan tahap cleaning dengan format csv
df.to_csv("Database_Seara_Data_Clean.csv", index=False)