1. Import Library

In [116]:
import pandas as pd

2. Load Dataset

In [117]:
df = pd.read_excel("C:/Users/r/OneDrive/Documents/doc saya/coding/project team fg/Recruitment-Analytics-Energy-Mining/data/Database Seara Data.xlsx")
print(df.head(1))

                Timestamp                     Nama Lengkap  \
0 2026-01-27 02:56:47.327  Aarif Rahmaan Jalaluddin Faqiih

                Email Nomor WhatsApp     Domisili  \
0  aarifrjf@gmail.com   082242458593  Jawa Tengah

  Apakah Anda Mahasiswa / Fresh Graduate Pekerjaan & Instansi Saat Ini  \
0                                     Ya                     Mahasiswa

  Tools yang Ingin Dipelajari            Target Join Komunitas  \
0             Python, Tableau  Cari Kerja, Upskill, Networking

  Tau Seara Data Dari Mana?  ... Upskill Networking  Switch Career  Excel  \
0                  LinkedIn  ...       1          1              0      0

   Python  Power BI  SQL  Looker Studio  Tableau  Databases
0       1         0    0              0        1          0

[1 rows x 23 columns]

3. Data Understanding

In [118]:
# cek jumlah baris dan kolom
df.shape

(682, 23)

In [119]:
# cek tipe data dan jumlah non-null per kolom
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Timestamp                               682 non-null    datetime64[us]
 1   Nama Lengkap                            682 non-null    str
 2   Email                                   682 non-null    str
 3   Nomor WhatsApp                          682 non-null    str
 4   Domisili                                682 non-null    str
 5   Apakah Anda Mahasiswa / Fresh Graduate  682 non-null    str
 6   Pekerjaan & Instansi Saat Ini           682 non-null    object
 7   Tools yang Ingin Dipelajari             682 non-null    str
 8   Target Join Komunitas                   682 non-null    str
 9   Tau Seara Data Dari Mana?               682 non-null    str
 10  Column 1                                682 non-null    str
 11  Provinsi                                682 non-null    str
 12  Cari Kerja                              682 non-null    int64
 13  Upskill                                 682 non-null    int64
 14  Networking                              682 non-null    int64
 15  Switch Career                           682 non-null    int64
 16  Excel                                   682 non-null    int64
 17  Python                                  682 non-null    int64
 18  Power BI                                682 non-null    int64
 19  SQL                                     682 non-null    int64
 20  Looker Studio                           682 non-null    int64
 21  Tableau                                 682 non-null    int64
 22  Databases                               682 non-null    int64
dtypes: datetime64[us](1), int64(11), object(1), str(10)
memory usage: 122.7+ KB

In [120]:
# cek statistik deskriptif data
df.describe()

,Timestamp,Cari Kerja,Upskill,Networking,Switch Career,Excel,Python,Power BI,SQL,Looker Studio,Tableau,Databases
count,682,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000
mean,2026-01-28 20:42:02.652212,0.661290,0.913490,0.766862,0.400293,0.774194,0.806452,0.756598,0.824047,0.587977,0.655425,0.719941
min,2026-01-17 20:22:18.629000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026-01-19 10:01:39.747250,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,2026-01-21 08:08:29.092000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,2026-01-24 19:31:28.081500,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2026-05-17 20:37:28.636000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,0.473618,0.281322,0.423140,0.490317,0.418419,0.395369,0.429451,0.381060,0.492561,0.475578,0.449357

In [121]:
# cek tipe data setiap kolom
df.dtypes

Timestamp                                 datetime64[us]
Nama Lengkap                                         str
Email                                                str
Nomor WhatsApp                                       str
Domisili                                             str
Apakah Anda Mahasiswa / Fresh Graduate               str
Pekerjaan & Instansi Saat Ini                     object
Tools yang Ingin Dipelajari                          str
Target Join Komunitas                                str
Tau Seara Data Dari Mana?                            str
Column 1                                             str
Provinsi                                             str
Cari Kerja                                         int64
Upskill                                            int64
Networking                                         int64
Switch Career                                      int64
Excel                                              int64
Python                                             int64
Power BI                                           int64
SQL                                                int64
Looker Studio                                      int64
Tableau                                            int64
Databases                                          int64
dtype: object

In [122]:
# cek 2 baris terakhir apakah ada data yang terpotong
df.tail(1)

,Timestamp,Nama Lengkap,Email,Nomor WhatsApp,Domisili,Apakah Anda Mahasiswa / Fresh Graduate,Pekerjaan & Instansi Saat Ini,Tools yang Ingin Dipelajari,Target Join Komunitas,Tau Seara Data Dari Mana?,...,Upskill,Networking,Switch Career,Excel,Python,Power BI,SQL,Looker Studio,Tableau,Databases
681,2026-01-22 13:20:05,Zura Aulia,zuraaa12@gmail.com,085288769002,Jakarta,Ya,-,"Excel, SQL, Python, Tableau","Upskill, Networking",LinkedIn,...,1,1,0,1,1,0,1,0,1,0

In [123]:
# list semua nama kolom untuk cek apakah ada typo pada nama kolom
df.columns.tolist()

['Timestamp',
 'Nama Lengkap',
 'Email',
 'Nomor WhatsApp',
 'Domisili',
 'Apakah Anda Mahasiswa / Fresh Graduate',
 'Pekerjaan & Instansi Saat Ini',
 'Tools yang Ingin Dipelajari',
 'Target Join Komunitas',
 'Tau Seara Data Dari Mana?',
 'Column 1',
 'Provinsi',
 'Cari Kerja',
 'Upskill',
 'Networking',
 'Switch Career',
 'Excel',
 'Python',
 'Power BI',
 'SQL',
 'Looker Studio',
 'Tableau',
 'Databases']

4. Data Preparation

In [124]:
# cek kolom nama lengkap
print(df["Nama Lengkap"].head(20))

0     Aarif Rahmaan Jalaluddin Faqiih
1                 Abdullah Rajab Sani
2                       Abdur Rochman
3              Abdurrahman Qeis Ahmad
4                  Abid Maulana Akbar
5                  Abimanyu Priyatno
6                 Achmad Chilmi Syifa
7               Achmad jamaah firdaus
8                 Achmad Kurniansyah
9                 Addo Adantya Abiesa
10                        Ade Krisna
11                Ade Krisna Subagyo
12                          Ade Mutia
13                   Ade Tri Oktavian
14                         Adek Putri
15                 Adhyatnika Nugraha
16            Adi Syah Putra Simbolon
17           Adinda Dwi Nur Rahmawati
18                   Adinda Dwi Putri
19                Adinda Putri Satya
Name: Nama Lengkap, dtype: str

In [125]:
# cek nama lengkap yang formatnya kapital semua
df[df["Nama Lengkap"] == df["Nama Lengkap"].str.upper()]["Nama Lengkap"]

67                   AMANG MISBAH
174            DIMAS ARIE PRASOJO
266         GILANG SIDIK RAMADHAN
308                   ILI NOVIANA
404    MUHAMAD RIZA BUDI PRATAMA
524         REFIKA FITRIA GUNAWAN
533               REZA OKTAVIANI
617            SRI AINUN LATHIFAH
Name: Nama Lengkap, dtype: str

In [126]:
# ubah format Nama Lengkap
df["Nama Lengkap"] = df["Nama Lengkap"].str.strip().str.title()

In [127]:
# Mengganti nama kolom sesuai ketentuan
df = df.rename(columns={
    "Tools yang Ingin Dipelajari": "Kemampuan Karyawan",
    "Target Join Komunitas": "Target Masuk Perusahaan",
    "Tau Seara Data Dari Mana?": "Mengetahui Perusahaan Dari Mana?",
    "Apakah Anda Mahasiswa / Fresh Graduate": "Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate"
})

In [128]:
# menghapus kolom yang tidak digunakan
df = df.drop(columns=["Pekerjaan & Instansi Saat Ini", "Column 1", "Domisili"])

In [129]:
# ubah tipe data timestamp jadi date
df["Timestamp"] = pd.to_datetime(df["Timestamp"]).dt.normalize()

In [130]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 20 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Timestamp                                                            682 non-null    datetime64[us]
 1   Nama Lengkap                                                         682 non-null    str
 2   Email                                                                682 non-null    str
 3   Nomor WhatsApp                                                       682 non-null    str
 4   Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate  682 non-null    str
 5   Kemampuan Karyawan                                                   682 non-null    str
 6   Target Masuk Perusahaan                                              682 non-null    str
 7   Mengetahui Perusahaan Dari Mana?                                     682 non-null    str
 8   Provinsi                                                             682 non-null    str
 9   Cari Kerja                                                           682 non-null    int64
 10  Upskill                                                              682 non-null    int64
 11  Networking                                                           682 non-null    int64
 12  Switch Career                                                        682 non-null    int64
 13  Excel                                                                682 non-null    int64
 14  Python                                                               682 non-null    int64
 15  Power BI                                                             682 non-null    int64
 16  SQL                                                                  682 non-null    int64
 17  Looker Studio                                                        682 non-null    int64
 18  Tableau                                                              682 non-null    int64
 19  Databases                                                            682 non-null    int64
dtypes: datetime64[us](1), int64(11), str(8)
memory usage: 106.7 KB

In [131]:
print("\nKolom Setelah Preparation")
print(df.columns.tolist())

Kolom Setelah Preparation
['Timestamp', 'Nama Lengkap', 'Email', 'Nomor WhatsApp', 'Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate', 'Kemampuan Karyawan', 'Target Masuk Perusahaan', 'Mengetahui Perusahaan Dari Mana?', 'Provinsi', 'Cari Kerja', 'Upskill', 'Networking', 'Switch Career', 'Excel', 'Python', 'Power BI', 'SQL', 'Looker Studio', 'Tableau', 'Databases']

5. Data Cleaning

In [132]:
# Menghapus spasi di awal dan akhir pada seluruh kolom kategorikal
string_cols = df.select_dtypes(include=["object", "string"]).columns

df[string_cols] = df[string_cols].apply(lambda col: col.str.strip())

In [133]:
df = df.drop_duplicates(
    subset=["Nama Lengkap", "Email", "Nomor WhatsApp"]
)

print(len(df))

654

In [134]:
# cek lagi duplikat by nama lengkap
duplicate_name = df[df.duplicated(subset="Nama Lengkap", keep=False)]
duplicate_name.sort_values("Nama Lengkap")

,Timestamp,Nama Lengkap,Email,Nomor WhatsApp,Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate,Kemampuan Karyawan,Target Masuk Perusahaan,Mengetahui Perusahaan Dari Mana?,Provinsi,Cari Kerja,Upskill,Networking,Switch Career,Excel,Python,Power BI,SQL,Looker Studio,Tableau,Databases
59,2026-01-20,Alief Akbar,alivenata@gmail.com,08119365633,Tidak,"Hadoop, Hive Server","Upskill, Networking",LinkedIn,Jakarta,0,1,1,0,0,0,0,0,0,0,0
60,2026-01-24,Alief Akbar,alivenata@gmail.com,081219365633,Tidak,Tableau,Networking,LinkedIn,Jakarta,0,0,1,0,0,0,0,0,0,1,0
116,2026-01-18,Athaya Akbar Ramdani,athayaramdani74@gmail.com,081387006088,Ya,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jawa Timur,1,1,1,0,1,1,1,1,1,1,1
117,2026-02-11,Athaya Akbar Ramdani,athayaramdani74@gmail.com,091387006088,Ya,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",Instagram,Jawa Timur,1,1,1,0,1,1,1,1,1,1,1
288,2026-01-18,Hendry Wijaya,hendrywijaya628@gmail.com,085213567627,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jawa Barat,1,1,1,0,1,1,1,1,1,1,1
289,2026-01-18,Hendry Wijaya,Hendrywijaya628@gmail.com,085213567267,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jawa Barat,1,1,1,0,1,1,1,1,1,1,1
345,2026-01-21,Khoirunnisa,khoirunjavinda@gmail.com,087863483496,Ya,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jawa Tengah,1,1,1,0,1,1,1,1,1,1,1
346,2026-01-21,Khoirunnisa,nisairun670@gmail.com,081334198736,Ya,"Excel, SQL, Python","Cari Kerja, Upskill, Networking, Switch Career",Teman,Jawa Timur,1,1,1,1,1,1,0,1,0,0,0
393,2026-03-19,Monika Hermiani Yolanda Simamora,monikasimamora8@gmail.com,0882 7125 4635,Ya,"Python, Power BI, Databases, Tableau","Cari Kerja, Upskill, Networking",Teman,Jawa Barat,1,1,1,0,0,1,1,0,0,1,1
392,2026-03-17,Monika Hermiani Yolanda Simamora,monikasimamora8@gmail.com,088271254635,Ya,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",Teman,Jawa Barat,1,1,1,0,1,1,1,1,1,1,1
424,2026-01-20,Muhammad Fauzi,muhammadfauzi231100@gmail.com,082288334096,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jawa Barat,1,1,1,0,1,1,1,1,1,1,1
425,2026-04-09,Muhammad Fauzi,Muha,082288334096,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill",Teman,Jawa Barat,1,1,0,0,1,1,1,1,1,1,1
426,2026-01-18,Muhammad Fiqih Hidayat,mhmmdfqhhidayat@gmail.com,089602816543,Ya,"Excel, SQL, Python, Power BI, Databases","Cari Kerja, Upskill, Networking, Switch Career",LinkedIn,Banten,1,1,1,1,1,1,1,1,0,0,1
427,2026-01-24,Muhammad Fiqih Hidayat,mhmmdfqhhidayat@gmail.com,089692816543,Ya,Python,"Cari Kerja, Upskill, Networking",LinkedIn,Banten,1,1,1,0,0,1,0,0,0,0,0
498,2026-01-18,Nurul Hidayah,nurulhdy2994@gmail.com,088294512101,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking, Switch Career",LinkedIn,Jawa Barat,1,1,1,1,1,1,1,1,1,1,1
499,2026-01-24,Nurul Hidayah,nurul.dieselone@gmail.com,085161622910,Tidak,"SQL, Python, Power BI, Looker Studio, Tableau","Upskill, Networking, Switch Career",LinkedIn,Jawa Barat,0,1,1,1,0,1,1,1,1,1,0
525,2026-01-21,Regina Mai Anggriani Br Sitanggang,reginamaianggriani@gmail.com,08994688875,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jakarta,1,1,1,0,1,1,1,1,1,1,1
526,2026-01-23,Regina Mai Anggriani Br Sitanggang,reginamaianggriani@gmail.com,081261621330,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...","Cari Kerja, Upskill, Networking",LinkedIn,Jakarta,1,1,1,0,1,1,1,1,1,1,1
560,2026-01-20,Risya Atma Nuura,Risya.atmanuura@gmail.com,082354633633 / 08114433633,Tidak,"Excel, SQL, Power BI, Tableau","Upskill, Networking",LinkedIn,Jawa Timur,0,1,1,0,1,0,1,1,0,1,0
561,2026-02-11,Risya Atma Nuura,risya.atmanuura@gmail.com,08114433633,Tidak,Power BI,"Cari Kerja, Upskill, Switch Career",LinkedIn,Kalimantan Selatan,1,1,0,1,0,0,1,0,0,0,0

In [135]:
# Menghapus data duplikat by Nama Lengkap
df = df.drop_duplicates(subset="Nama Lengkap", keep="first")

print(len(df))

644

In [136]:
df.info()

<class 'pandas.DataFrame'>
Index: 644 entries, 0 to 681
Data columns (total 20 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Timestamp                                                            644 non-null    datetime64[us]
 1   Nama Lengkap                                                         644 non-null    str
 2   Email                                                                644 non-null    str
 3   Nomor WhatsApp                                                       644 non-null    str
 4   Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate  644 non-null    str
 5   Kemampuan Karyawan                                                   644 non-null    str
 6   Target Masuk Perusahaan                                              644 non-null    str
 7   Mengetahui Perusahaan Dari Mana?                                     644 non-null    str
 8   Provinsi                                                             644 non-null    str
 9   Cari Kerja                                                           644 non-null    int64
 10  Upskill                                                              644 non-null    int64
 11  Networking                                                           644 non-null    int64
 12  Switch Career                                                        644 non-null    int64
 13  Excel                                                                644 non-null    int64
 14  Python                                                               644 non-null    int64
 15  Power BI                                                             644 non-null    int64
 16  SQL                                                                  644 non-null    int64
 17  Looker Studio                                                        644 non-null    int64
 18  Tableau                                                              644 non-null    int64
 19  Databases                                                            644 non-null    int64
dtypes: datetime64[us](1), int64(11), str(8)
memory usage: 105.7 KB

In [137]:
# menghapus kolom yang memuat informasi pribadi
df = df.drop(columns=["Nomor WhatsApp", "Email"])

In [138]:
# Cek apakah ada missing value
df.isnull().sum()

Timestamp                                                              0
Nama Lengkap                                                           0
Apakah Anda Memiliki Pengalaman Lebih Dari 1 Tahun / Fresh Graduate    0
Kemampuan Karyawan                                                     0
Target Masuk Perusahaan                                                0
Mengetahui Perusahaan Dari Mana?                                       0
Provinsi                                                               0
Cari Kerja                                                             0
Upskill                                                                0
Networking                                                             0
Switch Career                                                          0
Excel                                                                  0
Python                                                                 0
Power BI                                                               0
SQL                                                                    0
Looker Studio                                                          0
Tableau                                                                0
Databases                                                              0
dtype: int64

In [139]:
# simpan data yang sudah menyelesaikan tahap cleaning dengan format csv
df.to_csv("Database_Seara_Data_Clean.csv", index=False)